#define POWER_VOLTAGE_IN_MIN				11000
#define POWER_BATT_CELLS					4
#define POWER_BATT_VOLT_DISCHARGEOFF		3200	*POWER_BATT_CELLS
#define POWER_BATT_VOLT_DISCHARGEON		    3300	*POWER_BATT_CELLS
#define POWER_BATT_VOLT_CHARGEON			3900	*POWER_BATT_CELLS
#define POWER_BATT_VOLT_CHARGEOFF			4200	*POWER_BATT_CELLS

#define RELAYS_DDR	DDRB
#define RELAYS_PORT PORTB
#define RELAYS_PIN	PINB

#define RELAY_COMPUTER 1
#define RELAY_COMPUTER_ON		{setbit(RELAYS_DDR, RELAY_COMPUTER,1);  setbit(RELAYS_PORT,	RELAY_COMPUTER, 1); }
#define RELAY_COMPUTER_OFF		{setbit(RELAYS_DDR, RELAY_COMPUTER,1); setbit(RELAYS_PORT,	RELAY_COMPUTER, 0); }
#define RELAY_COMPUTER_STATE    (getbit(RELAYS_PORT, RELAY_COMPUTER) > 0 ? 1:0)

#define RELAY_CHARGE 0
#define RELAY_CHARGE_ON			{setbit(RELAYS_DDR, RELAY_CHARGE,1);  setbit(RELAYS_PORT,	RELAY_CHARGE, 1); }
#define RELAY_CHARGE_OFF	    {setbit(RELAYS_DDR, RELAY_CHARGE,1); setbit(RELAYS_PORT,	RELAY_CHARGE, 0); }
#define RELAY_CHARGE_STATE      (getbit(RELAYS_PORT, RELAY_CHARGE) > 0 ? 1:0)

#define RELAY_WIRELESS_UNIT	 3
#define RELAY_WIRELESS_UNIT_ON		   {setbit(RELAYS_DDR, RELAY_WIRELESS_UNIT ,1);  setbit(RELAYS_PORT,	RELAY_WIRELESS_UNIT, 1); }
#define RELAY_WIRELESS_UNIT_OFF		   {setbit(RELAYS_DDR, RELAY_WIRELESS_UNIT, 1); setbit(RELAYS_PORT,	RELAY_WIRELESS_UNIT, 0); }
#define RELAY_WIRELESS_UNIT_STATE      (getbit(RELAYS_PORT, RELAY_WIRELESS_UNIT) > 0 ? 1:0)

#define RELAY_FAN 2
#define RELAY_FAN_ON			{setbit(RELAYS_DDR, RELAY_FAN,1);  setbit(RELAYS_PORT,	RELAY_FAN, 1); }
#define RELAY_FAN_OFF			{setbit(RELAYS_DDR, RELAY_FAN,1); setbit(RELAYS_PORT,	RELAY_FAN, 0); }
#define RELAY_FAN_STATE			(getbit(RELAYS_PORT, RELAY_FAN) > 0 ? 1:0)

#define RELAY_MAIN	 5
#define RELAY_MAIN_ON			{setbit(RELAYS_DDR, RELAY_MAIN,1);  setbit(RELAYS_PORT,	RELAY_MAIN, 1); }
#define RELAY_MAIN_OFF			{setbit(RELAYS_DDR, RELAY_MAIN,1); setbit(RELAYS_PORT,	RELAY_MAIN, 0); }
#define RELAY_MAIN_STATE		(getbit(RELAYS_PORT, RELAY_MAIN) > 0 ? 1:0)

#define RELAY_HEAT	 4
#define RELAY_HEAT_ON			{setbit(RELAYS_DDR, RELAY_HEAT,1);  setbit(RELAYS_PORT,	RELAY_HEAT, 1); }
#define RELAY_HEAT_OFF			{setbit(RELAYS_DDR, RELAY_HEAT,1); setbit(RELAYS_PORT,	RELAY_HEAT, 0); }
#define RELAY_HEAT_STATE		(getbit(RELAYS_PORT, RELAY_HEAT) > 0 ? 1:0)

#define RELAY_BACKLIGHT 5
#define RELAY_BACKLIGHT_ON	    {setbit(DDRA, RELAY_BACKLIGHT,1);  setbit(PORTA,	RELAY_BACKLIGHT, 1); }
#define RELAY_BACKLIGHT_OFF		{setbit(DDRA, RELAY_BACKLIGHT,1);  setbit(PORTA,	RELAY_BACKLIGHT, 0); }
#define RELAY_BACKLIGHT_STATE   (getbit(PORTA, RELAY_BACKLIGHT) > 0 ? 1:0)

#define RELAY_COMP_BUTTON 7
#define RELAY_COMP_BUTTON_ON	    {setbit(RELAYS_DDR, RELAY_COMP_BUTTON,1);  setbit(RELAYS_PORT,	RELAY_COMP_BUTTON, 1); }
#define RELAY_COMP_BUTTON_OFF		{setbit(RELAYS_DDR, RELAY_COMP_BUTTON,1);  setbit(RELAYS_PORT,	RELAY_COMP_BUTTON, 0); }
#define RELAY_COMP_BUTTON_STATE   (getbit(RELAYS_PORT, RELAY_COMP_BUTTON) > 0 ? 1:0)

#define WATCHDOG_SEC_TO_RESET		60*5
#define WATCHDOG_SEC_TO_RESET_PAUSE	60*120
#define WATCHDOG_SEC_TO_RESET_FIRST	60*5
#define WATCHDOG_SEC_TO_POWERON		10
